behaviors:
  CarBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.0025
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
      gail:
        strength: 0.1
        demo_path: Demos/final3.demo
        use_actions: false

    behavioral_cloning: 
      demo_path: Demos/final3.demo
      steps: 750000
      strength: 0.2

    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 264
    max_steps: 50000000
    summary_freq: 100000
    threaded: true